esphome:
  name: t-relay
    # Force all relays OFF immediately at boot
  on_boot:
    priority: -200
    then:
      - switch.turn_off: rel_low
      - switch.turn_off: rel_med
      - switch.turn_off: rel_high

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "INSERT YOUR API KEY"

ota:
  - platform: esphome
    password: "INSERT YOUR PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# --- Relay definitions ---
# Fan relays (active HIGH → inverted: false)
switch:
  - platform: gpio
    id: rel_low
    pin:
      number: GPIO21
      inverted: false
    restore_mode: ALWAYS_OFF   # always start OFF

  - platform: gpio
    id: rel_med
    pin:
      number: GPIO19
      inverted: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: rel_high
    pin:
      number: GPIO18
      inverted: false
    restore_mode: ALWAYS_OFF

  # Optional: fourth relay as master power
  # - platform: gpio
  #   id: rel_master
  #   pin:
  #     number: GPIO5
  #     inverted: false
  #   restore_mode: ALWAYS_OFF

# --- Scripts to manage fan speeds ---
# Ensures only one relay is active at a time
script:
  - id: set_speed_low
    then:
      - switch.turn_on: rel_low
      - switch.turn_off: rel_med
      - switch.turn_off: rel_high

  - id: set_speed_med
    then:
      - switch.turn_off: rel_low
      - switch.turn_on: rel_med
      - switch.turn_off: rel_high

  - id: set_speed_high
    then:
      - switch.turn_off: rel_low
      - switch.turn_off: rel_med
      - switch.turn_on: rel_high

  - id: set_speed_off
    then:
      - switch.turn_off: rel_low
      - switch.turn_off: rel_med
      - switch.turn_off: rel_high

# --- Auto-off timer configuration ---
# Exposed to Home Assistant as a number (0–120 minutes)
number:
  - platform: template
    name: "AC400 Auto-Off Timer"
    id: auto_off_timer
    optimistic: true
    min_value: 0
    max_value: 120
    step: 5
    unit_of_measurement: "min"

# --- Scripts ---
script:
  - id: set_speed_low
    then:
      - switch.turn_on: rel_low
      - switch.turn_off: rel_med
      - switch.turn_off: rel_high

  - id: set_speed_med
    then:
      - switch.turn_off: rel_low
      - switch.turn_on: rel_med
      - switch.turn_off: rel_high

  - id: set_speed_high
    then:
      - switch.turn_off: rel_low
      - switch.turn_off: rel_med
      - switch.turn_on: rel_high

  - id: set_speed_off
    then:
      - switch.turn_off: rel_low
      - switch.turn_off: rel_med
      - switch.turn_off: rel_high

  # Auto shutdown script (runs in background, restarts if triggered again)
  - id: auto_shutdown
    mode: restart
    parameters:
      minutes: int
    then:
      - if:
          condition:
            lambda: "return minutes > 0;"
          then:
            - delay: !lambda "return (minutes * 60000);"
            - fan.turn_off: ac400_fan

# --- Fan entity ---
fan:
  - platform: template
    name: "AC400 Fan"
    id: ac400_fan
    speed_count: 3

    on_turn_on:
      # Default state is OFF, user must select speed
      - script.execute: set_speed_off
      # Start auto shutdown timer with current value
      - script.execute:
          id: auto_shutdown
          minutes: !lambda "return (int)id(auto_off_timer).state;"

    on_turn_off:
      - script.execute: set_speed_off

    on_speed_set:
      - lambda: |-
          if (x == 1) {
            id(set_speed_low).execute();
          } else if (x == 2) {
            id(set_speed_med).execute();
          } else if (x == 3) {
            id(set_speed_high).execute();
          }
# --- Utility buttons ---
button:
  - platform: restart
    name: "Restart AC400-T-relay"
