esphome:
  name: t-relay
    # Force all relays OFF immediately at boot
  on_boot:
    priority: -200
    then:
      - switch.turn_off: rel_low
      - switch.turn_off: rel_med
      - switch.turn_off: rel_high

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "INSERT YOUR API KEY"

ota:
  - platform: esphome
    password: "INSERT YOUR PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# --- Relay definitions ---
# Fan relays (active HIGH → inverted: false)
switch:
  - platform: gpio
    id: rel_low
    pin:
      number: GPIO21
      inverted: false
    restore_mode: ALWAYS_OFF   # always start OFF

  - platform: gpio
    id: rel_med
    pin:
      number: GPIO19
      inverted: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: rel_high
    pin:
      number: GPIO18
      inverted: false
    restore_mode: ALWAYS_OFF

  # Optional: fourth relay as master power
  # - platform: gpio
  #   id: rel_master
  #   pin:
  #     number: GPIO5
  #     inverted: false
  #   restore_mode: ALWAYS_OFF

# --- Scripts to manage fan speeds ---
# Ensures only one relay is active at a time
script:
  - id: set_speed_low
    then:
      - switch.turn_on: rel_low
      - switch.turn_off: rel_med
      - switch.turn_off: rel_high

  - id: set_speed_med
    then:
      - switch.turn_off: rel_low
      - switch.turn_on: rel_med
      - switch.turn_off: rel_high

  - id: set_speed_high
    then:
      - switch.turn_off: rel_low
      - switch.turn_off: rel_med
      - switch.turn_on: rel_high

  - id: set_speed_off
    then:
      - switch.turn_off: rel_low
      - switch.turn_off: rel_med
      - switch.turn_off: rel_high

# --- Single fan entity exposed to Home Assistant ---
fan:
  - platform: template
    name: "AC400 Fan"
    id: ac400_fan
    speed_count: 3

    on_turn_on:
      # Start in OFF state, user must select a speed
      - script.execute: set_speed_off

    on_turn_off:
      - script.execute: set_speed_off

    on_speed_set:
      - lambda: |-
          if (x == 1) {
            id(set_speed_low).execute();
          } else if (x == 2) {
            id(set_speed_med).execute();
          } else if (x == 3) {
            id(set_speed_high).execute();
          }

# --- Utility buttons ---
button:
  - platform: restart
    name: "Restart AC400-T-relay"
